"""client.py module.

This module defines a Client class for interacting with an API using a provided API handler.

"""

from typing import Any, Dict, Optional

from owmTestTask.client.api_handler import BaseApiHandler


class Client(object):
    """This class represents a client for interacting with an API using a provided API handler.

    Attributes:
        api_handler (BaseApiHandler): An instance of BaseApiHandler for handling API requests.

    """

    def __init__(self, api_handler: BaseApiHandler = None) -> None:
        """Initialize the Client.

        Args:
            api_handler (BaseApiHandler): An instance of BaseApiHandler for handling API requests.

        """
        self.api_handler = api_handler
        self.request = self.api_handler.get_request()

    @property
    def request(self) -> Optional[Dict[str, Any]]:
        """Get the API request.

        This property returns the API request generated by the handler.

        Returns:
            Optional[Dict[str, Any]]: The API request dictionary.

        """
        return self._request

    @request.setter
    def request(self, request_value):
        self._request = request_value
